#include "core/Transaction.hpp"

#include "crypto/hash.h"

#include <set>
#include <sstream>
#include <stdexcept>
#include <utility>

namespace nodo::core {

namespace {

constexpr std::size_t MAX_EXPLICIT_INPUT_COIN_LOTS = 128;
constexpr std::size_t MAX_COIN_LOT_ID_LENGTH = 256;

std::string extractField(
    const std::string& serialized,
    const std::string& key
) {
    const std::string prefix = key + "=";
    const std::size_t start = serialized.find(prefix);

    if (start == std::string::npos) {
        throw std::invalid_argument("Missing serialized Transaction field: " + key);
    }

    const std::size_t valueStart = start + prefix.size();
    std::size_t valueEnd = serialized.find(';', valueStart);

    if (valueEnd == std::string::npos) {
        valueEnd = serialized.find('}', valueStart);
    }

    if (valueEnd == std::string::npos || valueEnd <= valueStart) {
        throw std::invalid_argument("Invalid serialized Transaction field: " + key);
    }

    return serialized.substr(valueStart, valueEnd - valueStart);
}

bool hasField(
    const std::string& serialized,
    const std::string& key
) {
    return serialized.find(key + "=") != std::string::npos;
}

std::string extractTransactionPayload(
    const std::string& serialized
) {
    const std::string prefix = "payload=TransactionPayload{";
    const std::string suffix = ";signatureBundle=";

    const std::size_t payloadPrefixStart = serialized.find(prefix);

    if (payloadPrefixStart == std::string::npos) {
        throw std::invalid_argument("Serialized Transaction payload not found.");
    }

    const std::size_t payloadStart = payloadPrefixStart + std::string("payload=").size();
    const std::size_t payloadEnd = serialized.find(suffix, payloadStart);

    if (payloadEnd == std::string::npos || payloadEnd <= payloadStart) {
        throw std::invalid_argument("Serialized Transaction payload is malformed.");
    }

    return serialized.substr(payloadStart, payloadEnd - payloadStart);
}

bool isSafeCoinLotInputId(
    const std::string& value
) {
    if (value.empty() || value.size() > MAX_COIN_LOT_ID_LENGTH) {
        return false;
    }

    /*
     * Keep transaction payload parsing unambiguous.
     * CoinLot ids generated by Nodo use letters, digits, underscores and hashes,
     * so rejecting structural delimiters is safe and prevents parser confusion.
     */
    for (char character : value) {
        if (character == ';' ||
            character == ',' ||
            character == '[' ||
            character == ']' ||
            character == '{' ||
            character == '}' ||
            character == ' ' ||
            character == '\t' ||
            character == '\n' ||
            character == '\r') {
            return false;
        }
    }

    return true;
}

bool hasDuplicateInputCoinLotIds(
    const std::vector<std::string>& inputCoinLotIds
) {
    std::set<std::string> seen;

    for (const auto& inputCoinLotId : inputCoinLotIds) {
        if (!seen.insert(inputCoinLotId).second) {
            return true;
        }
    }

    return false;
}

bool areInputCoinLotIdsStructurallyValid(
    const std::vector<std::string>& inputCoinLotIds
) {
    if (inputCoinLotIds.size() > MAX_EXPLICIT_INPUT_COIN_LOTS) {
        return false;
    }

    if (hasDuplicateInputCoinLotIds(inputCoinLotIds)) {
        return false;
    }

    for (const auto& inputCoinLotId : inputCoinLotIds) {
        if (!isSafeCoinLotInputId(inputCoinLotId)) {
            return false;
        }
    }

    return true;
}

std::string serializeInputCoinLotIds(
    const std::vector<std::string>& inputCoinLotIds
) {
    std::ostringstream oss;

    oss << "[";

    for (std::size_t index = 0; index < inputCoinLotIds.size(); ++index) {
        if (index != 0) {
            oss << ",";
        }

        oss << inputCoinLotIds[index];
    }

    oss << "]";

    return oss.str();
}

std::vector<std::string> parseInputCoinLotIds(
    const std::string& serializedInputCoinLotIds
) {
    if (serializedInputCoinLotIds.size() < 2 ||
        serializedInputCoinLotIds.front() != '[' ||
        serializedInputCoinLotIds.back() != ']') {
        throw std::invalid_argument("Serialized input CoinLot id list is malformed.");
    }

    std::vector<std::string> inputCoinLotIds;

    const std::string content =
        serializedInputCoinLotIds.substr(
            1,
            serializedInputCoinLotIds.size() - 2
        );

    if (content.empty()) {
        return inputCoinLotIds;
    }

    std::size_t start = 0;

    while (start <= content.size()) {
        const std::size_t commaPosition =
            content.find(',', start);

        const std::size_t end =
            commaPosition == std::string::npos
                ? content.size()
                : commaPosition;

        const std::string value =
            content.substr(start, end - start);

        if (!isSafeCoinLotInputId(value)) {
            throw std::invalid_argument("Serialized input CoinLot id is unsafe.");
        }

        inputCoinLotIds.push_back(value);

        if (commaPosition == std::string::npos) {
            break;
        }

        start = commaPosition + 1;
    }

    if (!areInputCoinLotIdsStructurallyValid(inputCoinLotIds)) {
        throw std::invalid_argument("Serialized input CoinLot id list is invalid.");
    }

    return inputCoinLotIds;
}

std::vector<std::string> extractInputCoinLotIdsFromPayload(
    const std::string& payload
) {
    if (!hasField(payload, "inputLots")) {
        return {};
    }

    return parseInputCoinLotIds(
        extractField(
            payload,
            "inputLots"
        )
    );
}

} // namespace

std::string transactionTypeToString(TransactionType type) {
    switch (type) {
        case TransactionType::TRANSFER:
            return "TRANSFER";

        case TransactionType::MINT_REWARD:
            return "MINT_REWARD";

        case TransactionType::LOCK_SECURITY:
            return "LOCK_SECURITY";

        case TransactionType::UNLOCK_SECURITY:
            return "UNLOCK_SECURITY";

        case TransactionType::VALIDATOR_REGISTER:
            return "VALIDATOR_REGISTER";

        case TransactionType::VALIDATOR_VOTE:
            return "VALIDATOR_VOTE";

        case TransactionType::PENALTY:
            return "PENALTY";

        case TransactionType::BURN:
            return "BURN";

        default:
            return "UNKNOWN";
    }
}

TransactionType transactionTypeFromString(const std::string& value) {
    if (value == "TRANSFER") {
        return TransactionType::TRANSFER;
    }

    if (value == "MINT_REWARD") {
        return TransactionType::MINT_REWARD;
    }

    if (value == "LOCK_SECURITY") {
        return TransactionType::LOCK_SECURITY;
    }

    if (value == "UNLOCK_SECURITY") {
        return TransactionType::UNLOCK_SECURITY;
    }

    if (value == "VALIDATOR_REGISTER") {
        return TransactionType::VALIDATOR_REGISTER;
    }

    if (value == "VALIDATOR_VOTE") {
        return TransactionType::VALIDATOR_VOTE;
    }

    if (value == "PENALTY") {
        return TransactionType::PENALTY;
    }

    if (value == "BURN") {
        return TransactionType::BURN;
    }

    throw std::invalid_argument("Unknown TransactionType: " + value);
}

bool isMintTransaction(TransactionType type) {
    return type == TransactionType::MINT_REWARD;
}

bool isSecurityLockTransaction(TransactionType type) {
    return type == TransactionType::LOCK_SECURITY ||
           type == TransactionType::UNLOCK_SECURITY;
}

bool requiresUserSignature(TransactionType type) {
    return type == TransactionType::TRANSFER ||
           type == TransactionType::LOCK_SECURITY ||
           type == TransactionType::UNLOCK_SECURITY ||
           type == TransactionType::VALIDATOR_REGISTER ||
           type == TransactionType::VALIDATOR_VOTE ||
           type == TransactionType::BURN;
}

Transaction::Transaction(
    TransactionType type,
    std::string fromAddress,
    std::string toAddress,
    utils::Amount amount,
    utils::Amount fee,
    std::uint64_t nonce,
    std::int64_t timestamp
)
    : Transaction(
          type,
          std::move(fromAddress),
          std::move(toAddress),
          amount,
          fee,
          nonce,
          timestamp,
          {}
      ) {}

Transaction::Transaction(
    TransactionType type,
    std::string fromAddress,
    std::string toAddress,
    utils::Amount amount,
    utils::Amount fee,
    std::uint64_t nonce,
    std::int64_t timestamp,
    std::vector<std::string> inputCoinLotIds
)
    : m_id(""),
      m_type(type),
      m_fromAddress(std::move(fromAddress)),
      m_toAddress(std::move(toAddress)),
      m_amount(amount),
      m_fee(fee),
      m_nonce(nonce),
      m_timestamp(timestamp),
      m_inputCoinLotIds(std::move(inputCoinLotIds)),
      m_signatureBundle(),
      m_hasSignatureBundle(false) {
    if (!areInputCoinLotIdsStructurallyValid(m_inputCoinLotIds)) {
        throw std::invalid_argument("Invalid explicit input CoinLot id list.");
    }

    if (m_type != TransactionType::TRANSFER && !m_inputCoinLotIds.empty()) {
        throw std::invalid_argument("Only TRANSFER transactions can declare input CoinLot ids.");
    }

    m_id = computeTransactionIdFromPayload(signingPayload());
}

const std::string& Transaction::id() const {
    return m_id;
}

TransactionType Transaction::type() const {
    return m_type;
}

const std::string& Transaction::fromAddress() const {
    return m_fromAddress;
}

const std::string& Transaction::toAddress() const {
    return m_toAddress;
}

utils::Amount Transaction::amount() const {
    return m_amount;
}

utils::Amount Transaction::fee() const {
    return m_fee;
}

std::uint64_t Transaction::nonce() const {
    return m_nonce;
}

std::int64_t Transaction::timestamp() const {
    return m_timestamp;
}

const std::vector<std::string>& Transaction::inputCoinLotIds() const {
    return m_inputCoinLotIds;
}

bool Transaction::hasExplicitInputCoinLotIds() const {
    return !m_inputCoinLotIds.empty();
}

bool Transaction::hasSignatureBundle() const {
    return m_hasSignatureBundle;
}

const crypto::SignatureBundle& Transaction::signatureBundle() const {
    if (!m_hasSignatureBundle) {
        throw std::logic_error("Transaction has no SignatureBundle attached.");
    }

    return m_signatureBundle;
}

void Transaction::attachSignatureBundle(
    const crypto::SignatureBundle& signatureBundle
) {
    if (signatureBundle.empty()) {
        throw std::invalid_argument("Empty SignatureBundle rejected by Transaction.");
    }

    m_signatureBundle = signatureBundle;
    m_hasSignatureBundle = true;
}

std::string Transaction::signingPayload() const {
    std::ostringstream oss;

    /*
     * Deterministic ordering is critical.
     *
     * If two nodes serialize the same transaction differently,
     * signatures and transaction IDs will not match.
     */
    oss << "TransactionPayload{"
        << "type=" << transactionTypeToString(m_type)
        << ";from=" << m_fromAddress
        << ";to=" << m_toAddress
        << ";amountRaw=" << m_amount.rawUnits()
        << ";feeRaw=" << m_fee.rawUnits();

    /*
     * Backward compatibility:
     * Do not add inputLots=[] for legacy automatic-input transactions. This
     * keeps older accepted transaction ids stable while allowing new explicit
     * input transactions to commit the exact lots being spent.
     */
    if (!m_inputCoinLotIds.empty()) {
        oss << ";inputLots=" << serializeInputCoinLotIds(m_inputCoinLotIds);
    }

    oss << ";nonce=" << m_nonce
        << ";timestamp=" << m_timestamp
        << "}";

    return oss.str();
}

std::string Transaction::serialize() const {
    std::ostringstream oss;

    oss << "Transaction{"
        << "id=" << m_id
        << ";payload=" << signingPayload();

    if (m_hasSignatureBundle) {
        oss << ";signatureBundle=" << m_signatureBundle.serialize();
    } else {
        oss << ";signatureBundle=NONE";
    }

    oss << "}";

    return oss.str();
}

bool Transaction::isStructurallyValid(
    const crypto::CryptoPolicy& policy,
    crypto::SecurityContext context
) const {
    if (m_id.empty()) {
        return false;
    }

    if (m_timestamp <= 0) {
        return false;
    }

    if (m_nonce == 0) {
        return false;
    }

    if (!m_amount.isPositive()) {
        return false;
    }

    if (m_fee.isNegative()) {
        return false;
    }

    if (!areInputCoinLotIdsStructurallyValid(m_inputCoinLotIds)) {
        return false;
    }

    if (m_type != TransactionType::TRANSFER && !m_inputCoinLotIds.empty()) {
        return false;
    }

    if (m_id != computeTransactionIdFromPayload(signingPayload())) {
        return false;
    }

    if (m_type == TransactionType::TRANSFER) {
        if (m_fromAddress.empty() || m_toAddress.empty()) {
            return false;
        }

        if (m_fromAddress == m_toAddress) {
            return false;
        }
    }

    if (requiresUserSignature(m_type)) {
        if (!m_hasSignatureBundle) {
            return false;
        }

        if (!m_signatureBundle.isValidForPolicy(policy, context)) {
            return false;
        }
    }

    return true;
}

std::string Transaction::computeTransactionIdFromPayload(
    const std::string& signingPayload
) {
    char output[65] = {0};
    nodo_hash_string(signingPayload.c_str(), output, sizeof(output));

    return std::string(output);
}

Transaction Transaction::deserializeForStateReplay(
    const std::string& serialized
) {
    if (serialized.rfind("Transaction{", 0) != 0) {
        throw std::invalid_argument("Serialized data is not a Transaction.");
    }

    const std::string serializedId = extractField(serialized, "id");
    const std::string payload = extractTransactionPayload(serialized);

    if (payload.rfind("TransactionPayload{", 0) != 0) {
        throw std::invalid_argument("Serialized Transaction payload is invalid.");
    }

    Transaction transaction(
        transactionTypeFromString(extractField(payload, "type")),
        extractField(payload, "from"),
        extractField(payload, "to"),
        utils::Amount::fromRawUnits(std::stoll(extractField(payload, "amountRaw"))),
        utils::Amount::fromRawUnits(std::stoll(extractField(payload, "feeRaw"))),
        static_cast<std::uint64_t>(std::stoull(extractField(payload, "nonce"))),
        std::stoll(extractField(payload, "timestamp")),
        extractInputCoinLotIdsFromPayload(payload)
    );

    if (transaction.id() != serializedId) {
        throw std::invalid_argument("Serialized Transaction id does not match payload.");
    }

    if (transaction.signingPayload() != payload) {
        throw std::invalid_argument("Transaction serialization round-trip failed.");
    }

    return transaction;
}

} // namespace nodo::core
